scenarios/CampaignMember - Member.yml, scenarios/CampaignMember-Member.yml, scenarios/CampaignMember-Success.yml, scenarios/FormTestValidatedinSalesForce.yml, scenarios/SalesForceAPITest.yml
Added test scenarios for SalesForce
- Lead validation
- Campaign Member (Member & Success status) validation
- SalesForce API Test
=> Add UAT/Example Scenarios

src/client/client-wrapper.ts, src/steps/account-field-equals.ts, src/steps/create-account.ts, src/steps/create-opportunity.ts, src/steps/delete-account.ts, src/steps/delete-opportunity.ts, src/steps/opportunity-field-equals.ts, test/client/client-wrapper.ts, test/steps/account-field-equals.ts, test/steps/campaign-member-field-equals.ts, test/steps/create-account.ts, test/steps/create-opportunity.ts, test/steps/delete-account.ts, test/steps/delete-opportunity.ts, test/steps/lead-field-equals.ts, test/steps/opportunity-field-equals.ts
- Added create, find by identifier and delete by identifier for account and opportunity in client wrapper
- Added create, field validation and delete steps for account and opportunity
Related Issues: #10, #11, #12, #13, #14, #15
=> Added Account and Opportunity Steps

src/client/client-wrapper.ts, src/steps/account-field-equals.ts, src/steps/campaign-member-field-equals.ts, src/steps/campaign-member-id-equals.ts, src/steps/delete-account.ts, src/steps/delete-opportunity.ts, src/steps/lead-field-equals.ts, src/steps/opportunity-field-equals.ts, test/client/client-wrapper.ts, test/steps/account-field-equals.ts, test/steps/campaign-member-field-equals.ts, test/steps/create-opportunity.ts, test/steps/delete-account.ts, test/steps/delete-opportunity.ts, test/steps/lead-field-equals.ts, test/steps/opportunity-field-equals.ts, tslint.json
- disabled lint rule on line exceed 100 characters and triple equals rule
- fixed some mislabeled comments
=> tslint cleanup and modification

src/steps/delete-opportunity.ts, test/steps/delete-opportunity.ts
- changed delete opportunity expression 'delete the salesforce accountwith (?<field>[a-zA-Z0-9_]+) (?<identifier>.+)' to 'delete the salesforce opportunity with (?<field>[a-zA-Z0-9_]+) (?<identifier>.+)'
=> Changed delete opportunity expression fomr account to opportunity

src/client/client-wrapper.ts
- will display authentication error message on step initialize
=> Display proper auth error message for salesforce

scenarios/SalesForceAccountAPITest.yml, scenarios/SalesForceContactAPITest.yml, scenarios/SalesForceOpportunityAPITest.yml
These are the SalesForce scenarios for Account, Opportunity and Contact
SalesForce API Test for Account
SalesForce API Test for Opportunity
SalesForce API Test for Contact
=> SalesForce New Objects scenarios

test/client/client-wrapper.ts
updated unit test related to contact in client wrapper
=> updated client wrapper unit tests

package-lock.json, package.json, src/core/base-step.ts, src/steps/account/account-field-equals.ts, src/steps/campaign-member/campaign-member-field-equals.ts, src/steps/contact/contact-field-equals.ts, src/steps/lead/lead-field-equals.ts, src/steps/opportunity/opportunity-field-equals.ts, test/steps/account/account-field-equals.ts, test/steps/campaign-member/campaign-member-field-equals.ts, test/steps/contact/contact-field-equals.ts, test/steps/lead/lead-field-equals.ts, test/steps/opportunity/opportunity-field-equals.ts, tslint.json
- implement compare function in base steps
- made operator specific messages in base steps
- updated unit tests for all entity's field validation steps
=> implemented operators in salesforce entities

src/core/base-step.ts
- change fail message for greater than and less than operators
- interchanged values being compared with less than and greater than
=> Fixed bug with greater than less than comparison

src/core/base-step.ts
- set value and actualValue to lower case before checking if it contains or not contains
=> contains operators are now case insensitive validation

package-lock.json, package.json, src/client/constants/operators.ts, src/core/base-step.ts, src/steps/account/account-field-equals.ts, src/steps/campaign-member/campaign-member-field-equals.ts, src/steps/contact/contact-field-equals.ts, src/steps/lead/lead-field-equals.ts, test/steps/account/account-field-equals.ts, tslint.json
- removed previous implementation of value comparison to be replaced with crank util implementation
=> applied crank util for field validation

test/steps/account/account-field-equals.ts, test/steps/campaign-member/campaign-member-field-equals.ts, test/steps/contact/contact-field-equals.ts, test/steps/lead/lead-field-equals.ts, test/steps/opportunity/opportunity-field-equals.ts
For #56 
Covered all util errors in the catch block
=> Util tests

src/core/base-step.ts, tslint.json
=> handled objects to be stringified before being compared

package-lock.json, package.json, src/core/base-step.ts, src/steps/account/account-field-equals.ts
- removed json object handler in base step and moved it to field validation step
- updated util
=> moved handling of jsonobjects in steps to be display on fail message

test/scenarios/Smooth Operators Scenarios/Account API with Operators.crank.yml, test/scenarios/Smooth Operators Scenarios/Campaign Member with Operators.crank.yml, test/scenarios/Smooth Operators Scenarios/Contact API  with Operators.crank.yml, test/scenarios/Smooth Operators Scenarios/Lead - Web-To-Lead with Operators.crank.yml, test/scenarios/Smooth Operators Scenarios/Lead API with Operators.crank.yml, test/scenarios/Smooth Operators Scenarios/Opportunity API with Operator.crank.yml
These are the ff. scenarios added:
- Account API with Operators.crank
- Campaign Member with Operators.crank
- Contact API  with Operators.crank
- Lead - Web-To-Lead with Operators.crank
- Lead API with Operators.crank
- Opportunity API with Operator.crank
=> Smooth Operators Scenarios

src/client/client-wrapper.ts, src/client/mixins/object-aware.ts, src/steps/object-create.ts, src/steps/object-delete.ts, src/steps/object-field-equals.ts, src/steps/object-update.ts
=> Implemented Object steps

src/steps/object-field-equals.ts, src/steps/object-update.ts, test/steps/object-delete.ts, test/steps/object-field-equals.ts, test/steps/object-update.ts
- Rearranged salesforce object check field fields order
- Changed salesforce object operator to required
- Added identifier field to salesforce object update and updated expression
- Updated unit tests
=> Salesforce Bug fixes

src/client/mixins/account-aware.ts, src/client/mixins/campaign-member-aware.ts, src/client/mixins/contact-aware.ts, src/client/mixins/lead-aware.ts, src/client/mixins/object-aware.ts, src/client/mixins/opportunity-aware.ts
This will simplify mixin code and ensure a future bugfix can easily be applied across all objects...
=> Refactor all mixins to use ObjectAwareMixin as their base

src/client/mixins/account-aware.ts, src/client/mixins/campaign-member-aware.ts, src/client/mixins/contact-aware.ts, src/client/mixins/lead-aware.ts, src/client/mixins/object-aware.ts, src/client/mixins/opportunity-aware.ts, src/steps/account/account-field-equals.ts, src/steps/campaign-member/campaign-member-field-equals.ts, src/steps/contact/contact-field-equals.ts, src/steps/lead/lead-field-equals.ts, src/steps/object-field-equals.ts, src/steps/opportunity/opportunity-field-equals.ts, test/client/client-wrapper.ts, test/steps/opportunity/opportunity-field-equals.ts
=> Fix asserting field values on objects with many custom fields

package-lock.json, package.json, src/steps/account/account-field-equals.ts, src/steps/campaign-member/campaign-member-field-equals.ts, src/steps/contact/contact-field-equals.ts, src/steps/lead/lead-field-equals.ts, src/steps/object-field-equals.ts, src/steps/opportunity/opportunity-field-equals.ts, test/steps/account/account-field-equals.ts, test/steps/campaign-member/campaign-member-field-equals.ts, test/steps/contact/contact-field-equals.ts, test/steps/lead/lead-field-equals.ts, test/steps/object-field-equals.ts, test/steps/opportunity/opportunity-field-equals.ts
- updated expression, operator description, and unit test for all salesforce object with new `set operators`
=> Added 'set' operators in all salesforce objects

package-lock.json, package.json
- Fixes confusing error message when `not be set` operator is used
- Resolves dependency security vulnerabilities
=> Resolve minor dependency-related issues

package-lock.json, package.json, src/core/base-step.ts, src/steps/account/account-field-equals.ts, src/steps/campaign-member/campaign-member-field-equals.ts, src/steps/contact/contact-field-equals.ts, src/steps/lead/lead-field-equals.ts, src/steps/object-field-equals.ts, src/steps/opportunity/opportunity-field-equals.ts, test/steps/campaign-member/campaign-member-field-equals.ts
Leveraged util.assert function across steps
=> Leveraged util.assert function across steps

src/steps/account/account-field-equals.ts, src/steps/campaign-member/campaign-member-field-equals.ts, src/steps/contact/contact-field-equals.ts, src/steps/lead/lead-field-equals.ts, src/steps/object-field-equals.ts, src/steps/opportunity/opportunity-field-equals.ts
Some messages that are an `Error` have been changed to `Fail`
=> Applied fails vs errors message changing

src/client/client-wrapper.ts, src/client/mixins/campaign-aware.ts, src/steps/campaign-member/campaign-member-field-equals.ts, src/steps/campaign-member/campaign-member-id-equals.ts, test/steps/campaign-member/campaign-member-field-equals.ts, test/steps/campaign-member/campaign-member-id-equals.ts
* Updated Campaign Member Steps to Display the Campaign Name when Available in `Campaign Name (ID)` format
=> Campaign name display

src/client/mixins/campaign-aware.ts
From `CampaignMember` to `Campaign`
=> Fixed object name typo :(

.circleci/config.yml, examples/caching-example-1.yml, package-lock.json, package.json, src/client/caching-client-wrapper.ts, src/core/cog.ts, src/core/grpc-server.ts, test/client/caching-client-wrapper.ts, test/core/cog.ts
Implemented caching for the salesforce cog. This primarily includes:
- Made proxy file cachingClientWrapper, which either routes methods to their original function, or returns a cached value
- Restructured grpc-server and cog.ts files to work with the cache
- Wrote new tests that ensure each method can both find the cache and route to the original method
=> Salesforce Caching

examples/bulk-create.yml, src/client/caching-client-wrapper.ts, src/client/mixins/object-aware.ts, src/steps/bulk-object-create.ts, test/steps/bulk-object-create.ts
Adding Bulk Create Object Step and Tests
=> Bulk Object Create Step

src/client/caching-client-wrapper.ts, src/steps/bulk-object-create.ts
Fix typos in the caching-client-wrapper
=> Bulk Create Object bug fix for caching client wrapper

src/steps/lead/lead-discover.ts, test/scenarios/DiscoverLead.crank.yml, test/steps/lead/lead-discover.ts
added step for discovering fields on a lead
=> Discover Lead Step

src/steps/opportunity/opportunity-create.ts
Fixing a bug with the records returned from the Create Opportunity step.
=> Opportunity Token Bug Fix

src/steps/bulk-object-create.ts, test/steps/bulk-object-create.ts
Added expected field that takes in the original CSV, so that we can pass along the original rows for any rows that fail.
=> List Import Error Handling

src/client/mixins/object-aware.ts, src/steps/bulk-object-create.ts
fixed timout error, as well as struct type error
=> Fixed misc problems

src/steps/bulk-object-create.ts
stringified step record response which was the root of the issue
=> List Import Struct type error fix

src/steps/object-create.ts, src/steps/object-delete.ts, src/steps/object-field-equals.ts, src/steps/object-update.ts
Changed the targetObject for 'Object' steps to 'Any Object'
=> Change targetObject to Any Object
